### ISSUE TITLE
Cant join

### ISSUE THREAD

**Issue by W3ldoo** [JackWhite20/Comix#2]
I cant join.
It throws "Disconnected"!

**Comment by JackWhite20** [comment]
Hey,
could you provide some more details about what exactly happens and how your setup is?

**Comment by W3ldoo** [comment]
Config: http://hastebin.com/emelobapiy.cpp
Status: http://hastebin.com/emejuqalah.dos
http://puu.sh/oexeD.png

**Comment by JackWhite20** [comment]
Try to change the target host ip in the config to either localhost or to the ip on which the target proxy is running on.

**Comment by W3ldoo** [comment]
Not working

**Comment by W3ldoo** [comment]
Sorry, its working! I changed the whitelist.json, because there came a error

**Comment by JackWhite20** [comment]
Okay cool, no problem :)
